import { useState } from 'react'
import { AnalysisResult } from '../types'
import {
  Briefcase, Building2, MapPin, Clock, DollarSign, Target, Sparkles,
  AlertCircle, FileEdit, X, Download, Loader2, CheckCircle, PlusCircle,
  Edit3, Trash2
} from 'lucide-react'
import { getCVTips } from '../utils/api'
import { useAuth } from '../context/AuthContext'
import jsPDF from 'jspdf'

interface Props {
  result: AnalysisResult
}

interface CVTip {
  section: string
  action: string
  tip: string
}

const ACTION_ICON: Record<string, React.ReactNode> = {
  'Add':                <PlusCircle className="w-4 h-4 text-emerald-400" />,
  'Edit':               <Edit3 className="w-4 h-4 text-indigo-400" />,
  'Rewrite':            <Edit3 className="w-4 h-4 text-purple-400" />,
  'Create New Section': <PlusCircle className="w-4 h-4 text-sky-400" />,
  'Remove':             <Trash2 className="w-4 h-4 text-rose-400" />,
}

const ACTION_COLOR: Record<string, string> = {
  'Add':                'bg-emerald-900/30 text-emerald-300 border border-emerald-800/50',
  'Edit':               'bg-indigo-900/30 text-indigo-300 border border-indigo-800/50',
  'Rewrite':            'bg-purple-900/30 text-purple-300 border border-purple-800/50',
  'Create New Section': 'bg-sky-900/30 text-sky-300 border border-sky-800/50',
  'Remove':             'bg-rose-900/30 text-rose-300 border border-rose-800/50',
}

export default function JobMatchingPage({ result }: Props) {
  const { guestUserId } = useAuth()
  const matches = result.job_matches
  const highMatches = matches.filter(m => m.match_score >= 80).length

  const [modalOpen, setModalOpen]     = useState(false)
  const [modalJob, setModalJob]       = useState<(typeof matches)[0] | null>(null)
  const [tips, setTips]               = useState<CVTip[]>([])
  const [tipsLoading, setTipsLoading] = useState(false)

  const openTips = async (match: (typeof matches)[0]) => {
    setModalJob(match)
    setTips([])
    setModalOpen(true)
    setTipsLoading(true)
    try {
      const data = await getCVTips(
        guestUserId,
        match.job.title,
        match.job.company,
        (match.job as any).required_skills ?? [],
        match.missing_skills,
        match.match_score,
      )
      setTips(data)
    } catch {
      setTips([{ section: 'Error', action: 'Edit', tip: 'Could not load tips. Please try again.' }])
    } finally {
      setTipsLoading(false)
    }
  }

  const downloadPDF = () => {
    if (!modalJob || tips.length === 0) return
    const doc   = new jsPDF({ unit: 'pt', format: 'a4' })
    const pageW = doc.internal.pageSize.getWidth()
    const margin = 48
    const maxW   = pageW - margin * 2
    let y = margin

    // ── Header ─────────────────────────────────────────────
    doc.setFillColor(99, 102, 241)
    doc.rect(0, 0, pageW, 6, 'F')

    doc.setFontSize(22)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(30, 41, 59)
    doc.text('CV Improvement Report', margin, (y += 30))

    doc.setFontSize(12)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 116, 139)
    doc.text(`${modalJob.job.title}  ·  ${modalJob.job.company}  ·  ${modalJob.match_score.toFixed(0)}% current match`, margin, (y += 20))

    y += 20
    doc.setDrawColor(203, 213, 225)
    doc.line(margin, y, pageW - margin, y)
    y += 24

    // ── Tips ───────────────────────────────────────────────
    tips.forEach((tip, i) => {
      const lines   = doc.setFontSize(10).splitTextToSize(tip.tip, maxW - 24)
      const boxH    = Math.max(70, lines.length * 14 + 42)

      if (y + boxH > 800) { doc.addPage(); y = margin }

      doc.setFillColor(248, 250, 252)
      doc.setDrawColor(226, 232, 240)
      doc.roundedRect(margin, y, maxW, boxH, 6, 6, 'FD')

      // number circle
      doc.setFillColor(99, 102, 241)
      doc.circle(margin + 16, y + 18, 9, 'F')
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(255, 255, 255)
      doc.text(String(i + 1), margin + 16, y + 21, { align: 'center' })

      // section + action
      doc.setFontSize(11)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(30, 41, 59)
      doc.text(tip.section, margin + 32, y + 20)

      doc.setFontSize(9)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(99, 102, 241)
      doc.text(`[${tip.action}]`, margin + 32 + doc.getTextWidth(tip.section) + 6, y + 20)

      // tip text
      doc.setFontSize(10)
      doc.setTextColor(71, 85, 105)
      doc.text(lines, margin + 12, y + 38)

      y += boxH + 10
    })

    // footer
    doc.setFontSize(8)
    doc.setTextColor(148, 163, 184)
    doc.text('Generated by Wasel AI Career Platform', margin, doc.internal.pageSize.getHeight() - 20)

    doc.save(`cv-tips-${modalJob.job.title.replace(/\s+/g, '-').toLowerCase()}.pdf`)
  }

  return (
    <div className="max-w-5xl mx-auto w-full">

      {/* Page Header */}
      <div className="bg-[#1e293b]/50 border border-slate-700/50 rounded-2xl p-8 mb-8 backdrop-blur-sm relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/10 rounded-full blur-[80px] pointer-events-none" />
        <h1 className="text-3xl font-bold text-white mb-2">Job Matching</h1>
        <p className="text-slate-400">Opportunities matched to your profile and skills</p>
      </div>

      {/* Stats Row */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        {[
          { label: 'Total Matches',     value: matches.length, icon: <Briefcase className="w-5 h-5 text-indigo-400" /> },
          { label: 'High Match (>80%)', value: highMatches,    icon: <Target className="w-5 h-5 text-emerald-400" /> },
          { label: 'New Today',         value: matches.length, icon: <Sparkles className="w-5 h-5 text-purple-400" /> },
        ].map(stat => (
          <div key={stat.label} className="bg-[#1e293b]/50 border border-slate-700/50 rounded-2xl p-6 flex flex-col justify-between">
            <div className="flex items-center justify-between mb-4">
              <span className="text-slate-400 text-sm font-medium">{stat.label}</span>
              {stat.icon}
            </div>
            <div className="text-4xl font-bold text-white">{stat.value}</div>
          </div>
        ))}
      </div>

      {/* Job Cards */}
      <div className="space-y-6">
        {matches.map((match, idx) => (
          <div key={idx} className="bg-[#1e293b]/50 border border-slate-700/50 rounded-2xl p-8 hover:bg-[#1e293b]/80 transition-colors backdrop-blur-sm">

            {/* Title + Badge */}
            <div className="flex flex-col md:flex-row md:items-start justify-between gap-4 mb-6">
              <div>
                <div className="flex items-center gap-4 mb-3">
                  <h2 className="text-2xl font-bold text-white">{match.job.title}</h2>
                  <div className={`px-3 py-1 rounded-full text-sm font-semibold whitespace-nowrap ${
                    match.match_score >= 80
                      ? 'bg-emerald-900/40 text-emerald-300 border border-emerald-700/50'
                      : match.match_score >= 60
                        ? 'bg-indigo-900/40 text-indigo-300 border border-indigo-700/50'
                        : 'bg-orange-900/40 text-orange-300 border border-orange-700/50'
                  }`}>
                    {match.match_score.toFixed(0)}% Match
                  </div>
                </div>
                <div className="flex flex-wrap items-center gap-6 text-sm text-slate-400">
                  <span className="flex items-center gap-1.5"><Building2 className="w-4 h-4 text-slate-500" />{match.job.company}</span>
                  <span className="flex items-center gap-1.5"><MapPin className="w-4 h-4 text-slate-500" />{match.job.location || 'Saudi Arabia'}</span>
                  {match.job.job_type && <span className="flex items-center gap-1.5"><Clock className="w-4 h-4 text-slate-500" />{match.job.job_type}</span>}
                  {match.job.salary_range && <span className="flex items-center gap-1.5"><DollarSign className="w-4 h-4 text-slate-500" />{match.job.salary_range}</span>}
                </div>
              </div>
            </div>

            {/* Description */}
            <p className="text-slate-300 text-sm leading-relaxed mb-6">
              {match.job.description.length > 250 ? match.job.description.substring(0, 250) + '...' : match.job.description}
            </p>

            {/* Match Explanation + Skills */}
            <div className="mb-6">
              <h4 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">Why it's a match</h4>
              <p className="text-sm text-slate-300 mb-4 bg-[#0f172a]/50 p-4 rounded-xl border border-slate-800">
                {match.match_explanation}
              </p>
              <div className="flex flex-wrap gap-2">
                {match.matched_skills.map(s => (
                  <span key={s} className="bg-[#0f172a] text-slate-300 border border-slate-700 px-3 py-1 rounded-full text-xs font-medium">{s}</span>
                ))}
                {match.missing_skills.map(s => (
                  <span key={s} className="bg-orange-900/20 text-orange-400 border border-orange-800/50 px-3 py-1 rounded-full text-xs font-medium flex items-center gap-1">
                    <AlertCircle className="w-3 h-3" />{s}
                  </span>
                ))}
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex items-center gap-3 mt-6 flex-wrap">
              <a
                href={match.job.apply_link || '#'}
                target="_blank"
                rel="noreferrer"
                className="bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 text-white px-6 py-2.5 rounded-xl font-semibold text-sm transition-all shadow-lg shadow-indigo-500/20"
              >
                Apply Now
              </a>
              <button
                onClick={() => openTips(match)}
                className="flex items-center gap-2 bg-[#0f172a] hover:bg-slate-800 text-slate-200 border border-slate-700/50 hover:border-indigo-500/50 px-5 py-2.5 rounded-xl font-semibold text-sm transition-all"
              >
                <FileEdit className="w-4 h-4 text-indigo-400" />
                Get CV Tips
              </button>
            </div>

          </div>
        ))}
      </div>

      {/* ── CV Tips Modal ───────────────────────────────────── */}
      {modalOpen && modalJob && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          {/* Backdrop */}
          <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={() => setModalOpen(false)} />

          {/* Panel */}
          <div className="relative w-full max-w-2xl max-h-[90vh] flex flex-col bg-[#0f172a] border border-slate-700/60 rounded-2xl shadow-2xl shadow-black/60 overflow-hidden">

            {/* Modal Header */}
            <div className="flex items-start justify-between p-6 border-b border-slate-800">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <FileEdit className="w-5 h-5 text-indigo-400" />
                  <h3 className="text-lg font-bold text-white">CV Improvement Tips</h3>
                </div>
                <p className="text-sm text-slate-400">
                  {modalJob.job.title} · {modalJob.job.company} · {modalJob.match_score.toFixed(0)}% current match
                </p>
              </div>
              <div className="flex items-center gap-2">
                {tips.length > 0 && (
                  <button
                    onClick={downloadPDF}
                    className="flex items-center gap-1.5 bg-indigo-600 hover:bg-indigo-500 text-white px-4 py-2 rounded-xl text-sm font-medium transition-colors"
                  >
                    <Download className="w-4 h-4" />
                    Download PDF
                  </button>
                )}
                <button onClick={() => setModalOpen(false)} className="p-2 rounded-xl hover:bg-slate-800 text-slate-400 hover:text-white transition-colors">
                  <X className="w-5 h-5" />
                </button>
              </div>
            </div>

            {/* Modal Body */}
            <div className="flex-1 overflow-y-auto p-6 space-y-4">
              {tipsLoading ? (
                <div className="flex flex-col items-center justify-center py-16 text-slate-400 gap-4">
                  <Loader2 className="w-8 h-8 animate-spin text-indigo-400" />
                  <p className="text-sm">Analyzing your CV against this role...</p>
                </div>
              ) : tips.length === 0 ? (
                <div className="text-center py-16 text-slate-500 text-sm">No tips available.</div>
              ) : (
                tips.map((tip, i) => (
                  <div key={i} className="bg-[#1e293b]/60 border border-slate-700/40 rounded-xl p-5">
                    <div className="flex items-center gap-3 mb-3">
                      <div className={`flex items-center gap-1.5 text-xs font-semibold px-2.5 py-1 rounded-full ${ACTION_COLOR[tip.action] ?? 'bg-slate-800 text-slate-300 border border-slate-700'}`}>
                        {ACTION_ICON[tip.action] ?? <CheckCircle className="w-4 h-4" />}
                        {tip.action}
                      </div>
                      <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">{tip.section}</span>
                    </div>
                    <p className="text-sm text-slate-200 leading-relaxed">{tip.tip}</p>
                  </div>
                ))
              )}
            </div>

            {/* Modal Footer */}
            {!tipsLoading && tips.length > 0 && (
              <div className="p-4 border-t border-slate-800 bg-[#0f172a]/80 flex items-center justify-between">
                <p className="text-xs text-slate-500">{tips.length} actionable improvements found</p>
                <button
                  onClick={downloadPDF}
                  className="flex items-center gap-1.5 bg-indigo-600 hover:bg-indigo-500 text-white px-4 py-2 rounded-xl text-sm font-medium transition-colors"
                >
                  <Download className="w-4 h-4" />
                  Save as PDF
                </button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
